[build]
command = "npm run build"
publish = "dist"

[context.production.environment]
GO_VERSION = "1.24.1"
NODE_VERSION = "23.6.0"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/blog/index.xml"
  [headers.values]
    access-control-allow-origin = "*"
